# Generated by Django 2.1.7 on 2021-04-29 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210429_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 29, 18, 33, 48, 740779)),
        ),
    ]
